fix: WebWorkerRuntime.ts
yasumu-org/yasumu pull request #148
Opened 2024-10-21 13:32 UTC by vr-varad

1. eval() - Can access variables and functions outside of its scope, making it risky and unpredictable.Will use new Function(code)() 
https://dev.to/spukas/everything-wrong-with-javascript-eval-35on
2. new Worker() requires a URL for the code, not the string of code 
it can be done by 
 - either putting the `WEB_WORKER_BOOTSTRAP` in another file or 
 - making a workerUrl using blob
 

```
const blob = new Blob([WEB_WORKER_BOOTSTRAP], { type: "application/javascript" });

// Create a URL for the Blob
const workerUrl = URL.createObjectURL(blob);

const worker = new Worker(workerUrl);

```

1. Can add proper error handling (adding more try catch) and worker termination in `WebWorkerRuntime` when not in use.

2024-10-21 13:33 UTC, vr-varad commented
@twlite Do I have to write tests for this?

2024-10-21 13:44 UTC, twlite commented
Yes, but we don't have tests setup rn.

2024-10-22 03:57 UTC, twlite requested changes

2024-10-22 03:57 UTC, twlite commented on packages/core/src/workspace/runtime/WebWorkerRuntime.ts
>        this.worker.onmessage = (event) => {
I guess this needs types.

2024-10-22 05:39 UTC, twlite approved these changes

2024-10-22 05:39 UTC, merged