feat: Testing Mocks
yasumu-org/yasumu pull request #163
Opened 2024-11-16 08:12 UTC by vr-varad

2024-11-16 08:30 UTC, twlite requested changes
can you test these via `yasumu.{mock}` api instead? For example, instead of instantiating `ApplicationMock`, you could do `yasumu.app.getName()`

2024-11-16 08:51 UTC, twlite requested changes
beforeAll hook is not needed for this, it is only useful in scenarios like

```ts
let workspace: Workspace;

beforeAll(async () => {
  workspace = await yasumu.openWorkspace({path})
})
```

2024-11-16 08:51 UTC, twlite commented on packages/testing/__test__/application.spec.ts
> +  let app: ApplicationMock;
```suggestion
  const app = yasumu.app;
```

2024-11-16 08:51 UTC, twlite commented on packages/testing/__test__/application.spec.ts
> +  beforeAll(() => {
```suggestion
```

2024-11-16 08:51 UTC, twlite commented on packages/testing/__test__/application.spec.ts
> +    app = yasumu.app;
```suggestion
```

2024-11-16 08:51 UTC, twlite commented on packages/testing/__test__/application.spec.ts
> +  });
```suggestion
```

2024-11-16 08:51 UTC, twlite commented on packages/testing/__test__/application.spec.ts
> +
```suggestion
```

2024-11-16 08:51 UTC, twlite commented on packages/testing/__test__/application.spec.ts
> +
```suggestion
```

2024-11-16 08:56 UTC, vr-varad commented
I have read the CLA Document and I hereby sign the CLA

2024-11-16 09:05 UTC, twlite requested changes

2024-11-16 09:05 UTC, twlite commented on packages/testing/__test__/command.spec.ts
> +    try {
```suggestion
    expect(yasumu.command.invoke('unknown')).rejects.toThrowError('Command unknown not found');
```

2024-11-16 09:05 UTC, twlite commented on packages/testing/__test__/command.spec.ts
> +      await command.invoke('unknown');
```suggestion
```

2024-11-16 09:05 UTC, twlite commented on packages/testing/__test__/command.spec.ts
> +    } catch (error) {
```suggestion
```

2024-11-16 09:05 UTC, twlite commented on packages/testing/__test__/command.spec.ts
> +      expect(error).toBeDefined();
```suggestion
```

2024-11-16 09:05 UTC, twlite commented on packages/testing/__test__/command.spec.ts
> +      expect(error.message).toMatch('Command unknown not found'); // Adjust error handling based on implementation
```suggestion
```

2024-11-16 09:05 UTC, twlite commented on packages/testing/__test__/command.spec.ts
> +    }
```suggestion
```

2024-11-16 10:36 UTC, twlite requested changes

2024-11-17 03:14 UTC, twlite approved these changes

2024-11-17 03:14 UTC, merged